title = "Antonino DiMaggio"
baseURL = "https://antoninodimaggio.com"
tags = []
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-168002660-1"
pygmentsUseClasses = true
minify = true
buildDrafts = false

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomy]
    tag = "tags"

[permalinks]
    posts = "/:slug"

[Params]
    headline = 'antonino dimaggio'
    subheadline = ""
    author = "Antonino DiMaggio"
    description = "Hello my name is Antonino â€” Tony for short. I live in New Jersey and work at Tesla. In the past, I worked on problems in renewable energy at NREL and studied computer science at Rutgers. I haphazardly write"
    logoSmall = "/images/profile_photo_1080_1080.jpg"
    twitterCardImg = "/images/default_summary_card_large_1440_720.jpg"
    favicon = "/images/favicon.ico"
    opengraphImage = "images/profile_photo_1080_1080.jpg"
    twitter = "tonyjdimaggio"
    linkedin = "antoninodimaggio"
    github = "antoninodimaggio"
    email = "antoninodimaggio@gmail.com"
    googleTagManager = ""
    copyright = true


[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1

[[menu.main]]
    name = "Posts"
    url  = "/#posts"
    weight = 2

[[menu.main]]
    name = "Subscribe"
    url  = "/#subscribe"
    weight = 3
